version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: flow-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminPassword
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
